"""create user tables

Revision ID: e24aaa463422
Revises: c5d0c3c2215d
Create Date: 2025-05-19 03:08:12.043568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24aaa463422'
down_revision: Union[str, None] = 'c5d0c3c2215d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_area',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_id', sa.UUID(), nullable=True),
    sa.Column('names', sa.String(length=100), nullable=False),
    sa.Column('lastnames', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['user_area.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['user_area.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_user')
    op.drop_table('user_role')
    op.drop_table('user_area')
    # ### end Alembic commands ###
